---
# tasks file for users_and_groups
# - name: Ensure group "somegroup" exists
- ansible.builtin.group:
    name: "dev"
    state: present
   with_items:
    - somegroup
    - billing
    - marketing
    - sales